name: "workflow-filters and Activities"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - closed

    paths-ignore:
      - README.md

    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print event type
        run: echo "this workflow job is executed for event-type ${{ github.event_name }}"